spring.application.name=gestao-empresarial

# Configuração de conexão com o banco
spring.datasource.url=jdbc:postgresql://localhost:5432/erp_simples
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Porta do servidor (opcional, 8080 é o padrão)
server.port=8080